### ISSUE TITLE
Most common errors with the Shadertoy utility

### ISSUE THREAD

**Issue by Vipitis** [pygfx/shadertoy#15]
This issue lists the most common issue with shadercode from Shadertoy.com when run through the wgpu-py utility. It serves as a task list and will be updated as PRs are merged. (the data is based on a filtered [dataset](https://huggingface.co/datasets/Vipitis/Shadertoys) I mined a while ago)

```md
number of shaders: 13576
number of valid shaders: 11264
number of errors during validation: 2175
number of value errors: 27
number of timeouts during validation: 10
number of panics during validation: 100
```
The most frequent errors are as follows: 
```wgsl
naga:: Composing 0's component type is not expected                                                        231
InvalidToken(LeftParen, [Identifier])                                                                      124
InvalidToken(In, [Token(Void), Token(Struct), TypeName])                                                   117
naga:: The `return` value None does not match the function return value                                    110
panic                                                                                                      100
SemanticError("Cannot apply the binary op to the arguments")                                                96
SemanticError("Unknown function 'dot'")                                                                     71
SemanticError("uniform/buffer blocks require layout(binding=X)")                                            71
naga:: Type flags TypeFlags(DATA | COPY | HOST_SHAREABLE) do not meet the required TypeFlags(CONSTRUCTIBLE) 61
SemanticError("Can't resolve type: IncompatibleOperands(\"Dot(Scalar { kind: Float, width: 4 }, _)\")")     58
SemanticError("Not implemented as constant expression: Normalize built-in function")                        55
SemanticError("Not implemented as constant expression: Acos built-in function")                             54
SemanticError("Not implemented as constant expression: Sqrt built-in function")                             50
PreprocessorError(DefineRedefined)                                                                          48
InvalidToken(Identifier("sampler2D"), [Token(RightParen)])                                                  42
naga:: The type is not constructible                                                                        40
SemanticError("Not implemented as constant expression: Cos built-in function")                              34
invalid Shader Code                                                                                         27
InvalidToken(Star, [Token(Semicolon)])                                                                      25
SemanticError("Not implemented as constant expression: Atan built-in function")                             22
SemanticError("Float literal is infinite")                                                                  21
SemanticError("Not implemented as constant expression: Radians built-in function")                          20
naga:: Local variable has a type [9] that can't be stored in a local variable.                              13
naga:: Local variable has a type [16] that can't be stored in a local variable.                             13
SemanticError("Can't lookup field on this type \"y\"")                                                      12
SemanticError("Can't lookup field on this type \"xz\"")                                                     11
other: timedout                                                                                             10
naga:: Local variable has a type [10] that can't be stored in a local variable.                              9
SemanticError("Not implemented as constant expression: Asin built-in function")                              9
SemanticError("Not implemented as constant expression: Log built-in function")                               9
SemanticError("Unknown function 'cos'")                                                                      8
SemanticError("Not implemented as constant expression: Sin built-in function")                               8
```
## Tasks list:
* in wgpu-py
- [x] pygfx/wgpu-py#428 (Unknown variable: iDate) +216 ~~(forgot to adjust the order in the docstring)~~
- [x] pygfx/wgpu-py#443 (Unknown variable: iChannel0, textures?) +92
- [x] pygfx/wgpu-py#453 (Unknown variable: iFrameRate) +4
- [ ] (Unknown function 'dot', the majority of these shaders seem to be from https://www.shadertoy.com/user/dr2, so it could be a very specific issue with their syntax.)

* in wgpu/naga
- [x] gfx-rs/wgpu#4644 (fall-through switch case block/panic glsl -> wgsl: Case values can only be integers) (maybe fixed with wgpu-native 0.18.1.2 this example now works: https://www.shadertoy.com/view/DtccWr)
- [ ] gfx-rs/wgpu#4549 (glsl -> spv: panic ~block.rs:2098:56)
- [ ] gfx-rs/wgpu#4773 (valid: panic ~variables.rs:336:28)
- [ ] gfx-rs/wgpu#4897 (Composing 0's component type is not expected)

**Comment by Korijn** [comment]
> @Korijn could you transfer this issue to the shadertoy repo?

Done!
